CREATE DATABASE TEAM_DB;

CREATE TABLE TB_TEAM (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TNAME VARCHAR(150) NOT NULL,
	TCODE VARCHAR(10) NOT NULL
);

INSERT INTO TB_TEAM(TCODE, TNAME) VALUES('DEVOPS', 'INFRA DEVOPS AMERICA');
INSERT INTO TB_TEAM(TCODE, TNAME) VALUES('ZLIMP', 'IMPLATACAO PRODUTO');